[package]
name = "forge-extensions-branch-templates"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
serde = { workspace = true }
uuid = { version = "1.0", features = ["v4"] }
utils = { path = "../../crates/utils" }
