[package]
name = "forge-extensions-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

# For TypeScript type generation
ts-rs = { workspace = true }

# Forge extensions
forge-extensions-omni = { path = "../omni" }